"""multi_tenant_user_id

Revision ID: 051877be6d50
Revises: e5cdb44ca11c
Create Date: 2026-05-08 15:18:44.062786

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '051877be6d50'
down_revision: str | Sequence[str] | None = 'e5cdb44ca11c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_DEFAULT = "user_default"

def upgrade() -> None:
    # Add user_id with a server_default so existing rows get the placeholder value.
    for table in ('accounts', 'audit_log', 'option_tickets', 'orders',
                  'screener_symbols', 'streak_state', 'tickets'):
        op.add_column(table, sa.Column(
            'user_id', sa.String(length=128),
            nullable=False, server_default=_DEFAULT,
        ))
        op.create_index(f'ix_{table}_user_id', table, ['user_id'], unique=False)

    # accounts: questrade_account_id uniqueness now per-user (drop global unique)
    op.drop_index(op.f('ix_accounts_questrade_account_id'), table_name='accounts')
    op.create_index(op.f('ix_accounts_questrade_account_id'), 'accounts', ['questrade_account_id'], unique=False)

    # screener_symbols: symbol uniqueness now per-user
    op.drop_index(op.f('ix_screener_symbols_symbol'), table_name='screener_symbols')
    op.create_index(op.f('ix_screener_symbols_symbol'), 'screener_symbols', ['symbol'], unique=False)

    # streak_state: user_id must be unique (one streak per user)
    op.drop_index('ix_streak_state_user_id', table_name='streak_state', if_exists=True)
    op.create_index('ix_streak_state_user_id', 'streak_state', ['user_id'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_column('tickets', 'user_id')
    op.drop_index(op.f('ix_streak_state_user_id'), table_name='streak_state')
    op.drop_column('streak_state', 'user_id')
    op.drop_index(op.f('ix_screener_symbols_user_id'), table_name='screener_symbols')
    op.drop_index(op.f('ix_screener_symbols_symbol'), table_name='screener_symbols')
    op.create_index(op.f('ix_screener_symbols_symbol'), 'screener_symbols', ['symbol'], unique=True)
    op.drop_column('screener_symbols', 'user_id')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_column('orders', 'user_id')
    op.drop_index(op.f('ix_option_tickets_user_id'), table_name='option_tickets')
    op.drop_column('option_tickets', 'user_id')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_column('audit_log', 'user_id')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_questrade_account_id'), table_name='accounts')
    op.create_index(op.f('ix_accounts_questrade_account_id'), 'accounts', ['questrade_account_id'], unique=True)
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
