"""screener_fundamentals

Revision ID: 1f688594b895
Revises: 90ed3f72c11f
Create Date: 2026-05-04 10:11:11.431847

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1f688594b895'
down_revision: str | Sequence[str] | None = '90ed3f72c11f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screener_scores', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('screener_scores', sa.Column('universe_source', sa.String(length=32), nullable=True))
    op.add_column('screener_scores', sa.Column('fundamental_score', sa.Numeric(precision=4, scale=3), nullable=False, server_default='0'))
    op.add_column('screener_scores', sa.Column('revenue_growth', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('screener_scores', sa.Column('net_income_growth', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('screener_scores', sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('screener_scores', sa.Column('eps_ttm', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('screener_scores', sa.Column('fundamental_error', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screener_scores', 'fundamental_error')
    op.drop_column('screener_scores', 'eps_ttm')
    op.drop_column('screener_scores', 'net_margin')
    op.drop_column('screener_scores', 'net_income_growth')
    op.drop_column('screener_scores', 'revenue_growth')
    op.drop_column('screener_scores', 'fundamental_score')
    op.drop_column('screener_scores', 'universe_source')
    op.drop_column('screener_scores', 'sector')
    # ### end Alembic commands ###
