"""init schema

Revision ID: 334697509213
Revises: 
Create Date: 2026-04-27 16:56:10.362554

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '334697509213'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questrade_account_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('primary_currency', sa.String(length=3), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('real_money_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_questrade_account_id'), 'accounts', ['questrade_account_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('streak_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consecutive_wins', sa.Integer(), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('last_outcome', sa.String(length=16), nullable=True),
    sa.Column('last_ticket_id', sa.UUID(), nullable=True),
    sa.Column('current_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('maintenance_excess', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'currency', name='uq_account_balance_currency')
    )
    op.create_index(op.f('ix_account_balances_account_id'), 'account_balances', ['account_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('setup_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume_confirm_multiple', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('time_stop_days', sa.Integer(), nullable=True),
    sa.Column('risk_pct', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('household_equity_at_creation', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('streak_multiplier_at_creation', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('position_size_shares', sa.Integer(), nullable=False),
    sa.Column('position_size_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('armed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('thesis', sa.String(length=2000), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_account_id'), 'tickets', ['account_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_symbol'), 'tickets', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('questrade_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_questrade_order_id'), 'orders', ['questrade_order_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_ticket_id'), 'orders', ['ticket_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('open_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('is_buy_and_hold', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', 'currency', name='uq_position_account_symbol_ccy')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_ticket_id'), 'fills', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_ticket_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_ticket_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_questrade_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_tickets_symbol'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_account_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_account_balances_account_id'), table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_table('streak_state')
    op.drop_table('settings')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_accounts_questrade_account_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
