"""earnings_dates

Revision ID: 3f514f5adb65
Revises: a8edf754a8f4
Create Date: 2026-05-05 09:06:36.743634

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3f514f5adb65'
down_revision: str | Sequence[str] | None = 'a8edf754a8f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('next_earnings_date', sa.DateTime(), nullable=True),
    sa.Column('last_eps_surprise_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_earnings_date', sa.DateTime(), nullable=True),
    sa.Column('avg_volume', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_dates_symbol'), 'earnings_dates', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_dates_symbol'), table_name='earnings_dates')
    op.drop_table('earnings_dates')
    # ### end Alembic commands ###
