"""add_screener_schema

Revision ID: 90ed3f72c11f
Revises: 334697509213
Create Date: 2026-04-29 21:20:23.786386

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '90ed3f72c11f'
down_revision: str | Sequence[str] | None = '334697509213'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_bars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('bar_date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'bar_date', name='uq_daily_bar_symbol_date')
    )
    op.create_index('ix_daily_bar_symbol_date', 'daily_bars', ['symbol', 'bar_date'], unique=False)
    op.create_index(op.f('ix_daily_bars_bar_date'), 'daily_bars', ['bar_date'], unique=False)
    op.create_index(op.f('ix_daily_bars_symbol'), 'daily_bars', ['symbol'], unique=False)
    op.create_table('screener_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tt_score', sa.Integer(), nullable=False),
    sa.Column('tt_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vcp_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('vcp_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('rs_raw', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ma_50', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ma_150', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ma_200', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_scores_symbol'), 'screener_scores', ['symbol'], unique=True)
    op.create_table('screener_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_symbols_symbol'), 'screener_symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_symbols_symbol'), table_name='screener_symbols')
    op.drop_table('screener_symbols')
    op.drop_index(op.f('ix_screener_scores_symbol'), table_name='screener_scores')
    op.drop_table('screener_scores')
    op.drop_index(op.f('ix_daily_bars_symbol'), table_name='daily_bars')
    op.drop_index(op.f('ix_daily_bars_bar_date'), table_name='daily_bars')
    op.drop_index('ix_daily_bar_symbol_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    # ### end Alembic commands ###
