"""options_and_exit_ladder

Revision ID: a8edf754a8f4
Revises: 1f688594b895
Create Date: 2026-05-04 16:30:21.212787

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a8edf754a8f4'
down_revision: str | Sequence[str] | None = '1f688594b895'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('premium_received', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('break_even', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('thesis', sa.String(length=2000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('premium_paid_to_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('position_ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['position_ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_tickets_account_id'), 'option_tickets', ['account_id'], unique=False)
    op.create_index(op.f('ix_option_tickets_status'), 'option_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_option_tickets_underlying_symbol'), 'option_tickets', ['underlying_symbol'], unique=False)
    op.add_column('tickets', sa.Column('exit_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'exit_plan')
    op.drop_index(op.f('ix_option_tickets_underlying_symbol'), table_name='option_tickets')
    op.drop_index(op.f('ix_option_tickets_status'), table_name='option_tickets')
    op.drop_index(op.f('ix_option_tickets_account_id'), table_name='option_tickets')
    op.drop_table('option_tickets')
    # ### end Alembic commands ###
