"""ticket_close_journal

Revision ID: e5cdb44ca11c
Revises: 3f514f5adb65
Create Date: 2026-05-05 20:36:33.703208

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e5cdb44ca11c'
down_revision: str | Sequence[str] | None = '3f514f5adb65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('close_notes', sa.String(length=2000), nullable=True))
    op.add_column('tickets', sa.Column('close_reason_tag', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'close_reason_tag')
    op.drop_column('tickets', 'close_notes')
    # ### end Alembic commands ###
